// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkmbK59dDdhRR7tugGmaPKUGReaLg9ud0',
    appId: '1:391127375889:web:d64aa3f4f956dc27e3d1b0',
    messagingSenderId: '391127375889',
    projectId: 'remoteconfigid',
    authDomain: 'remoteconfigid.firebaseapp.com',
    storageBucket: 'remoteconfigid.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8qHwPnZRXxnTU0UArcbnMLqscZE1AL50',
    appId: '1:391127375889:android:847f0180b54205fee3d1b0',
    messagingSenderId: '391127375889',
    projectId: 'remoteconfigid',
    storageBucket: 'remoteconfigid.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiV_A0b44U67-hdtbOdZf0Rkrnz50pKUw',
    appId: '1:391127375889:ios:2332e31e0c2c4fdee3d1b0',
    messagingSenderId: '391127375889',
    projectId: 'remoteconfigid',
    storageBucket: 'remoteconfigid.appspot.com',
    iosClientId: '391127375889-3lrg4j2t8qkpttvel45v84v5lhopr7lo.apps.googleusercontent.com',
    iosBundleId: 'com.xraph.plugin.fuwPluginExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiV_A0b44U67-hdtbOdZf0Rkrnz50pKUw',
    appId: '1:391127375889:ios:77f21a84dd18bd6be3d1b0',
    messagingSenderId: '391127375889',
    projectId: 'remoteconfigid',
    storageBucket: 'remoteconfigid.appspot.com',
    iosClientId: '391127375889-qffs4uh9q30p8qvhiha19al4eje7s0mh.apps.googleusercontent.com',
    iosBundleId: 'com.xraph.plugin.example',
  );
}
